name: CI - Benchmark
on:
  push:
    branches:
      - main
    paths:
      - "subjects/**"
      - "**/CI-bench.yml"

permissions:
  contents: write

jobs:
  benchmark:
    name: Create Benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Tools
        shell: bash
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - run: cargo install hyperfine

      # For Haskell
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: "9.2.8"
          cabal-version: "3.6.2.0"

      - name: Run the benchmark suite
        shell: bash
        continue-on-error: ${{ false }}
        run: |
          SHORT_COMMIT=$(git rev-parse --short=7 $GITHUB_SHA)
          OUTPUT_FILE=$(bash command.sh ci bench $SHORT_COMMIT)

          git fetch
          git checkout gh-pages

          if git log --oneline | grep $GITHUB_SHA; then
            echo "This commit has already been added"
            exit 1
          fi

          cat $OUTPUT_FILE
          cat results.json

          jq --argjson current \
            "$(cat $OUTPUT_FILE)" \
            '. += $current' results.json \
            > new-results.json
          mv new-results.json results.json

          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          git add results.json
          git commit -m "update($SHORT_COMMIT): $GITHUB_SHA"
          git push
