name: CI - Languages
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "subjects/**"

jobs:
  Rust:
    name: Validate Rust Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Test Rust
        shell: bash
        run: bash command.sh test -l rust

  C:
    name: Validate C Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Test Rust
        shell: bash
        run: bash command.sh test -l c
  Haskell:
    name: Validate Haskell Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: "9.2.8"
          cabal-version: "3.6.2.0"
      - name: Test Haskell
        shell: bash
        run: bash command.sh test -l haskell
